on:
  release:
    types: [published, created, edited]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm run test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
